language: r

env:
  - TRAVIS_NODE_VERSION="9.11.1"
cache:
  packages: yes
  directories:
    - $HOME/bin

install:
    - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
    - npm install -g cheerio

before_script:
  - Rscript -e 'blogdown::install_hugo()'

script:
  - ./download_packages.sh

before_deploy:
  - wget -qO- 'https://github.com/netlify/netlifyctl/releases/download/v0.3.2/netlifyctl-linux-amd64-0.3.2.tar.gz' | tar xvz
  - ls -laR ./content
  - ls -laR ./public

deploy:
  provider: script
  script:
    - 'if [ "$TRAVIS_BRANCH" != "master" ]; then ./netlifyctl deploy --draft --base-directory "public" --site-id "$NETLIFY_SITE_ID" --access-token "$NETLIFY_ACCESS_TOKEN"; else ./netlifyctl deploy --base-directory "public" --site-id "$NETLIFY_SITE_ID" --access-token "$NETLIFY_ACCESS_TOKEN"; fi'
  skip_cleanup: true
  on:
    all_branches: true
