language: r

cache:
  packages: yes
  directories:
    - $HOME/bin


before_script:
  - Rscript -e 'blogdown::install_hugo()'

script:
  - ./download_packages.sh

before_deploy:
  - wget -qO- 'https://github.com/netlify/netlifyctl/releases/download/v0.3.2/netlifyctl-linux-amd64-0.3.2.tar.gz' | tar xvz
  - ls -laR ./content
  - ls -laR ./public

deploy:
  provider: script
  script:
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./netlifyctl deploy --draft --base-directory "public" --site-id "$NETLIFY_SITE_ID" --access-token "$NETLIFY_ACCESS_TOKEN"; else ./netlifyctl deploy --base-directory "public" --site-id "$NETLIFY_SITE_ID" --access-token "$NETLIFY_ACCESS_TOKEN"; fi'
  skip_cleanup: true
  on:
    branch: master
