language: r
pandoc_version: 2.2.1

cache:
  packages: yes
  directories:
    - $HOME/bin

before_install:
  - nvm install node
  - nvm use node
  - npm install cheerio
  - npm install js-yaml
  - node --version

before_script:
  - Rscript -e 'blogdown::install_hugo()'

script:
  - ./download_packages.sh

before_deploy:
  - wget -qO- 'https://github.com/netlify/netlifyctl/releases/download/v0.3.2/netlifyctl-linux-amd64-0.3.2.tar.gz' | tar xvz
  - ls -laR ./content
  - ls -laR ./public

deploy:
  provider: script
  script:
    - 'if [ "$TRAVIS_BRANCH" != "master" ]; then ./netlifyctl deploy --draft --base-directory "public" --site-id "$NETLIFY_SITE_ID" --access-token "$NETLIFY_ACCESS_TOKEN"; else ./netlifyctl deploy --base-directory "public" --site-id "$NETLIFY_SITE_ID" --access-token "$NETLIFY_ACCESS_TOKEN"; fi'
  skip_cleanup: true
  on:
    all_branches: true

notifications:
  slack:
    secure: Id0J750ZSethSxB4dkWeEYxGtERd7awjoQ4qUW69cdzVjyadKgVQASp+QDFSDC73TwPrunYrEE1qghu7CvEoDXLb1cAaJSNGknmkoZ7XqNYF6z2emdzMv0maJHYclyBoXDwp7ak96Z8tH0vR0kf8aFm3yVimg756yuHdd7Vo7L6NeUKnaojRsnQFPFKV0FxBvC8ge288OWcO9KwUOlwFZ+/LlCAG+5b0CJD7hfGZCiXmCMvFCC9lmneo/NaxIVN06BwYLYBF/OfN/qLhkV38ai2RJcTR5PRYsiajOC/r+UDD6zljnuSLG/00FcvNpA5DkjKYBTKXZZ9W4MLOfAxExdhWG2CQGeA9ulV4n9VsRXP4lTpgdNvmZZfQSGdJTcV3QKWX0PbfKIMc64UkbTrFerTwmwVmyaejR6gcjDyL3+a48IQ6Ugss6sQ+WA5J240ydjRI/5YX5KGpHocsA5kLo0TOlpxpCftQ3SU4hBcLzmhHFGtQdK4XVohXlWcEiocIffGsbKfxCBpTGZMF/ngawxjyolG8dE7Lq6v0rzY8A3t0CzFoL/eVe53qzjwHDInZcC1MzfhSzJ7Ndc+NExWX7PkV52Ne1ubiex9uyJlW8N9waLf2yaYxFhigQaq5dXL+vsgcyig1xRnDrdqoZByr+JytzdLXsmEKYWD8IQmvq7s=
    on_success: never
    on_failure: always
