baseurl = "https://thirsty-morse-aa29ed.netlify.com"
languageCode = "en-us"
title = "Declare Design"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
uglyurls = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

# Home
#################
[[menu.main]]
  name = "Blog"
  url = "/post.html"
  weight = 1

[[menu.main]]
  name = "The Idea"
  url = "/page/package/DeclareDesign/articles/idea.html"
  weight = 2

[[menu.main]]
  name = "Design Library"
  url = "/page/package/DeclareDesign/articles/design_library.html"
  weight = 3

# Declare Design
#################
[[menu.main]]
  name = "Declare Design Home"
  url = "/page/package/DeclareDesign/readme.html"
  weight = 4

# randomizr
#################
[[menu.main]]
  name = "randomizr Home"
  url = "/page/package/randomizr/readme.html"
  weight = 5

# fabricatr
#################
[[menu.main]]
  name = "fabricatr Home"
  url = "/page/package/fabricatr/readme.html"
  weight = 6

# estimatr
#################
[[menu.main]]
  name = "estimatr Home"
  url = "/page/package/estimatr/readme.html"
  weight = 7

[params]
    description = "Declare and diagnose research designs to understand and improve them"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.3"

    [params.logo]
    url = "logo.png"
    width = 222
    height = 476
    alt = "Logo"
