baseurl = "https://thirsty-morse-aa29ed.netlify.com"
DefaultContentLanguage = "en"
title = "Declare Design"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentOptions = "linenos=table"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
uglyurls = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Params]
  subtitle = "Declare and diagnose research designs to understand and improve them"
# logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = false
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Graeme Blair • Jasper Cooper • Alexander Coppock • Macartan Humphreys"
# website = "yourwebsite.com"
  email = "contribute@declaredesign.org"
  github = "DeclareDesign"
  stackoverflow = "questions/tagged/declaredesign"
  
############################################
# Main Menu
############################################
[[menu.main]]
    name = "Blog"
    url = "/post.html"
    weight = 1

[[menu.main]]
    name = "The Idea"
    url = "/page/idea.html"
    weight = 2
    
[[menu.main]]
    name = "Design Library"
    url = "/page/design_library.html"
    weight = 3
    
[[menu.main]]
    identifier = "using_declare_design"
    name = "Using Declare Design"
    weight = 4
[[menu.main]]
    parent = "using_declare_design"
    name = "Getting Started"
    url = "/page/DeclareDesign.html"
    weight = 1
[[menu.main]]
    parent = "using_declare_design"
    name = "Custom Functions"
    url = "/page/custom_functions.html"
    weight = 2
[[menu.main]]
    parent = "using_declare_design"
    name = "Advanced Features"
    url = "/page/advanced_features.html"
    weight = 3
[[menu.main]]
    parent = "using_declare_design"
    name = "Companion Packages"
    url = "/page/companion_packages.html"
    weight = 4

[[menu.main]]
    name = "Ask for Help"
    url = "http://discuss.declaredesign.org"
    weight = 5

[[menu.main]]
    identifier = "packages"
    name = "Package"
    weight = 6
[[menu.main]]
    parent = "packages"
    name = "Declare Design"
    url = "/page/package/declaredesign/home.html"
    weight = 1
[[menu.main]]
    parent = "packages"
    name = "randomizr"
    url = "/page/package/randomizr/home.html"
    weight = 2
[[menu.main]]
    parent = "packages"
    name = "fabricatr"
    url = "/page/package/fabricatr/home.html"
    weight = 3
[[menu.main]]
    parent = "packages"
    name = "estimatr"
    url = "/page/package/estimatr/home.html"
    weight = 4
    
[[menu.main]]
    identifier = "vignettes"
    name = "Test Vignettes"
    weight = 7
[[menu.main]]
    parent = "vignettes"
    name = "Declare Design"
    url = "/page/package/declaredesign/vignettes.html"
    weight = 1
[[menu.main]]
    parent = "vignettes"
    name = "randomizr"
    url = "/page/package/randomizr/vignettes.html"
    weight = 2
[[menu.main]]
    parent = "vignettes"
    name = "fabricatr"
    url = "page/package/fabricatr/vignettes.html"
    weight = 3
[[menu.main]]
    parent = "vignettes"
    name = "estimatr"
    url = "page/package/estimatr/vignettes.html"
    weight = 4

